In [2]:
#1.What is python library? Why do you use python libraries?

# Python Library is collection of functions. It is reusable and Optimized

In [3]:
#2. What is difference between Numpy array and List?

# Arrays are homogenous. It takes lesser time to retrieve data
# List are heterogenous. It stores address of elements and not elements itself.


In [4]:
#3. Find the shape, size and dimensions of the following array?
import numpy as np
arr = np.array([[1,2,3,4],
 [5,6,7,8],
 [9,10,11,12]])



In [5]:
arr.shape

(3, 4)

In [6]:
arr.ndim

2

In [7]:
arr.size

12

In [8]:
#4.Write python co^e to access the first row of the following array?
arr = np.array([[1,2,3,4],
 [5,6,7,8],
 [9,10,11,12]])

arr[0,:]


array([1, 2, 3, 4])

In [9]:
#5. How ^o you access the element at the third row and fourth column from the given numpy array?

arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

arr[2,3]

12

In [10]:
#6. Write code to extract all odd-indexed elements from the given numpy array?



def oddnumber(arr):
     
    for i in (arr):
        for j in i:
            if j % 2 !=0:
                print(j)
                
                
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

oddnumber(arr)



1
3
5
7
9
11


In [11]:
#7. How can you generate a ran^om 3x3 matrix with values between 0 and 1?

arr1 = np.random.randint(0,2,(3,3))

print(arr1)

[[0 1 1]
 [0 0 0]
 [0 0 0]]


In [12]:
#8. Describe the ^ifference between np.random.rand and np.random.randn?
#And - The difference between rand and randn is that "rand" returns random numbers sampled from a uniform distribution over the interval [0,1), while randn return samples from a normal distribution with a mean of 0 and a variance of 1.


In [13]:
#9.Write the code to increase the dimensions of the following array

arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

np.expand_dims(arr,axis =0)


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [14]:
#10.how to transpose followuing array in numpy

arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

np.array(arr).T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [15]:
A = np.matrix([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

B = np.matrix([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

C = np.reshape(B,(4,3))

In [16]:
np.multiply(A,B)

matrix([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]])

In [17]:
A @ C

matrix([[ 70,  80,  90],
        [158, 184, 210],
        [246, 288, 330]])

In [18]:
A + B

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

In [19]:
A-B

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [20]:
B/A

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
#12. Which function in numpy can be used to swap the byte order of an array?
#Ans - .byteswap()

In [22]:
#13.What is the significance of np.linalg.inv function?
#Ans - It is used to calculate inverse of the matrix 


In [24]:
#14. What does np.reshape function do, and how it is used?
#Ans. np.reshape function shapes the array without chaning the data.


arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

arr1 = np.reshape(arr,(2,6))

arr1


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [25]:
#15.What is broadcasting in numpy?
#Ans . This allows us to perform mathematical operations on arrays of different shapes.An array with smaller shape is expanded to match shape of larger array.